input_data_path: 'data/raw/network_traffic_data.csv'
input_preprocessed_data_path: 'data/raw/network_traffic_data_prep.csv'
output_model_path: 'models/catclf.pkl'
metric_path: 'models/metrics.json'
splitting_params:
  val_size: 0.25
  random_state: 42
  shuffle: True
train_params:
  model_type: 'CatBoost'
  loss_function: 'MultiClass'
  random_state: 42
  n_estimators: 50
  iterations: 100
  learning_rate: 0.1
  depth: 5
  bagging_temperature: 0.2
  thread_count: -1
feature_params:
  features:
    - 'Destination Port'
    - 'Flow Duration'
    - 'Total Fwd Packets'
    - 'Total Backward Packets'
    - 'Total Length of Fwd Packets'
    - 'Total Length of Bwd Packets'
    - 'Fwd Packet Length Max'
    - 'Fwd Packet Length Min'
    - 'Fwd Packet Length Mean'
    - 'Fwd Packet Length Std'
    - 'Bwd Packet Length Max'
    - 'Bwd Packet Length Min'
    - 'Bwd Packet Length Mean'
    - 'Bwd Packet Length Std'
    - 'Flow Bytes/s'
    - 'Flow Packets/s'
    - 'Flow IAT Mean'
    - 'Flow IAT Std'
    - 'Flow IAT Max'
    - 'Flow IAT Min'
    - 'Fwd IAT Total'
    - 'Fwd IAT Mean'
    - 'Fwd IAT Std'
    - 'Fwd IAT Max'
    - 'Fwd IAT Min'
    - 'Bwd IAT Total'
    - 'Bwd IAT Mean'
    - 'Bwd IAT Std'
    - 'Bwd IAT Max'
    - 'Bwd IAT Min'
    - 'Fwd PSH Flags'
    - 'Bwd PSH Flags'
    - 'Fwd URG Flags'
    - 'Bwd URG Flags'
    - 'Fwd Header Length'
    - 'Bwd Header Length'
    - 'Fwd Packets/s'
    - 'Bwd Packets/s'
    - 'Min Packet Length'
    - 'Max Packet Length'
    - 'Packet Length Mean'
    - 'Packet Length Std'
    - 'Packet Length Variance'
    - 'FIN Flag Count'
    - 'SYN Flag Count'
    - 'RST Flag Count'
    - 'PSH Flag Count'
    - 'ACK Flag Count'
    - 'URG Flag Count'
    - 'CWE Flag Count'
    - 'ECE Flag Count'
    - 'Down/Up Ratio'
    - 'Average Packet Size'
    - 'Avg Fwd Segment Size'
    - 'Avg Bwd Segment Size'
    - 'Fwd Header Length.1'
    - 'Fwd Avg Bytes/Bulk'
    - 'Fwd Avg Packets/Bulk'
    - 'Fwd Avg Bulk Rate'
    - 'Bwd Avg Bytes/Bulk'
    - 'Bwd Avg Packets/Bulk'
    - 'Bwd Avg Bulk Rate'
    - 'Subflow Fwd Packets'
    - 'Subflow Fwd Bytes'
    - 'Subflow Bwd Packets'
    - 'Subflow Bwd Bytes'
    - 'Init_Win_bytes_forward'
    - 'Init_Win_bytes_backward'
    - 'act_data_pkt_fwd'
    - 'min_seg_size_forward'
    - 'Active Mean'
    - 'Active Std'
    - 'Active Max'
    - 'Active Min'
    - 'Idle Mean'
    - 'Idle Std'
    - 'Idle Max'
    - 'Idle Min'
  target_col: 'Label'
  cat_features: ['Destination Port']